### ISSUE TITLE
Vectorized version of find3d?

### ISSUE THREAD

**Issue by mulka** [strawlab/pymvg#6]
Is there a way to use find3d to triangulate multiple sets of 2d points into multiple 3d points in a vectorized version?

**Comment by astraw** [comment]
No, it doesn't exist in the API. I think it would not make much sense. Each triangulation has to build a new matrix, on which a singular value decomposition is then performed. I don't think the low level math libraries (lapack) has any alternative to scale this up.

If you need more speed, I've been working on this in rust: https://docs.rs/cam-geom and there is also https://docs.rs/cv-core
